use core::fmt;

#[repr(u16)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum PS2ScanCode {
    // Number row
    Esc,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    Minus,
    Equal,
    Backspace,

    // Top row
    Tab,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LeftBracket,
    RightBracket,
    Enter,
    LeftCtrl,

    // Home row
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Apostrophe,
    Backtick,

    // Bottom row
    LeftShift,
    Backslash,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Dot,
    Slash,
    RightShift,
    KeypadStar,
    LeftAlt,
    Space,
    CapsLock,

    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    NumLock,
    ScrollLock,

    // Keypad
    Keypad7,
    Keypad8,
    Keypad9,
    KeypadMinus,
    Keypad4,
    Keypad5,
    Keypad6,
    KeypadPlus,
    Keypad1,
    Keypad2,
    Keypad3,
    Keypad0,
    KeypadDot,

    // More function keys
    F11,
    F12,
    KeyReleased,
}

impl PS2ScanCode {
    pub fn from_scancode(code: u8) -> Option<Self> {
        match code {
            0x01 => Some(PS2ScanCode::Esc),
            0x02 => Some(PS2ScanCode::Key1),
            0x03 => Some(PS2ScanCode::Key2),
            0x04 => Some(PS2ScanCode::Key3),
            0x05 => Some(PS2ScanCode::Key4),
            0x06 => Some(PS2ScanCode::Key5),
            0x07 => Some(PS2ScanCode::Key6),
            0x08 => Some(PS2ScanCode::Key7),
            0x09 => Some(PS2ScanCode::Key8),
            0x0A => Some(PS2ScanCode::Key9),
            0x0B => Some(PS2ScanCode::Key0),
            0x0C => Some(PS2ScanCode::Minus),
            0x0D => Some(PS2ScanCode::Equal),
            0x0E => Some(PS2ScanCode::Backspace),
            0x0F => Some(PS2ScanCode::Tab),
            0x10 => Some(PS2ScanCode::Q),
            0x11 => Some(PS2ScanCode::W),
            0x12 => Some(PS2ScanCode::E),
            0x13 => Some(PS2ScanCode::R),
            0x14 => Some(PS2ScanCode::T),
            0x15 => Some(PS2ScanCode::Y),
            0x16 => Some(PS2ScanCode::U),
            0x17 => Some(PS2ScanCode::I),
            0x18 => Some(PS2ScanCode::O),
            0x19 => Some(PS2ScanCode::P),
            0x1A => Some(PS2ScanCode::LeftBracket),
            0x1B => Some(PS2ScanCode::RightBracket),
            0x1C => Some(PS2ScanCode::Enter),
            0x1D => Some(PS2ScanCode::LeftCtrl),
            0x1E => Some(PS2ScanCode::A),
            0x1F => Some(PS2ScanCode::S),
            0x20 => Some(PS2ScanCode::D),
            0x21 => Some(PS2ScanCode::F),
            0x22 => Some(PS2ScanCode::G),
            0x23 => Some(PS2ScanCode::H),
            0x24 => Some(PS2ScanCode::J),
            0x25 => Some(PS2ScanCode::K),
            0x26 => Some(PS2ScanCode::L),
            0x27 => Some(PS2ScanCode::Semicolon),
            0x28 => Some(PS2ScanCode::Apostrophe),
            0x29 => Some(PS2ScanCode::Backtick),
            0x2A => Some(PS2ScanCode::LeftShift),
            0x2B => Some(PS2ScanCode::Backslash),
            0x2C => Some(PS2ScanCode::Z),
            0x2D => Some(PS2ScanCode::X),
            0x2E => Some(PS2ScanCode::C),
            0x2F => Some(PS2ScanCode::V),
            0x30 => Some(PS2ScanCode::B),
            0x31 => Some(PS2ScanCode::N),
            0x32 => Some(PS2ScanCode::M),
            0x33 => Some(PS2ScanCode::Comma),
            0x34 => Some(PS2ScanCode::Dot),
            0x35 => Some(PS2ScanCode::Slash),
            0x36 => Some(PS2ScanCode::RightShift),
            0x37 => Some(PS2ScanCode::KeypadStar),
            0x38 => Some(PS2ScanCode::LeftAlt),
            0x39 => Some(PS2ScanCode::Space),
            0x3A => Some(PS2ScanCode::CapsLock),
            0x3B => Some(PS2ScanCode::F1),
            0x3C => Some(PS2ScanCode::F2),
            0x3D => Some(PS2ScanCode::F3),
            0x3E => Some(PS2ScanCode::F4),
            0x3F => Some(PS2ScanCode::F5),
            0x40 => Some(PS2ScanCode::F6),
            0x41 => Some(PS2ScanCode::F7),
            0x42 => Some(PS2ScanCode::F8),
            0x43 => Some(PS2ScanCode::F9),
            0x44 => Some(PS2ScanCode::F10),
            0x45 => Some(PS2ScanCode::NumLock),
            0x46 => Some(PS2ScanCode::ScrollLock),
            0x47 => Some(PS2ScanCode::Keypad7),
            0x48 => Some(PS2ScanCode::Keypad8),
            0x49 => Some(PS2ScanCode::Keypad9),
            0x4A => Some(PS2ScanCode::KeypadMinus),
            0x4B => Some(PS2ScanCode::Keypad4),
            0x4C => Some(PS2ScanCode::Keypad5),
            0x4D => Some(PS2ScanCode::Keypad6),
            0x4E => Some(PS2ScanCode::KeypadPlus),
            0x4F => Some(PS2ScanCode::Keypad1),
            0x50 => Some(PS2ScanCode::Keypad2),
            0x51 => Some(PS2ScanCode::Keypad3),
            0x52 => Some(PS2ScanCode::Keypad0),
            0x53 => Some(PS2ScanCode::KeypadDot),
            0x57 => Some(PS2ScanCode::F11),
            0x58 => Some(PS2ScanCode::F12),
            x if x > 0x80 => Some(PS2ScanCode::KeyReleased),
            _ => None,
        }
    }
}

impl PS2ScanCode {
    pub fn to_str(&self) -> &'static str {
        match self {
            // Number row
            PS2ScanCode::Esc => "Esc",
            PS2ScanCode::Key1 => "1",
            PS2ScanCode::Key2 => "2",
            PS2ScanCode::Key3 => "3",
            PS2ScanCode::Key4 => "4",
            PS2ScanCode::Key5 => "5",
            PS2ScanCode::Key6 => "6",
            PS2ScanCode::Key7 => "7",
            PS2ScanCode::Key8 => "8",
            PS2ScanCode::Key9 => "9",
            PS2ScanCode::Key0 => "0",
            PS2ScanCode::Minus => "-",
            PS2ScanCode::Equal => "=",
            PS2ScanCode::Backspace => "Backspace",

            // Top row
            PS2ScanCode::Tab => "Tab",
            PS2ScanCode::Q => "Q",
            PS2ScanCode::W => "W",
            PS2ScanCode::E => "E",
            PS2ScanCode::R => "R",
            PS2ScanCode::T => "T",
            PS2ScanCode::Y => "Y",
            PS2ScanCode::U => "U",
            PS2ScanCode::I => "I",
            PS2ScanCode::O => "O",
            PS2ScanCode::P => "P",
            PS2ScanCode::LeftBracket => "[",
            PS2ScanCode::RightBracket => "]",
            PS2ScanCode::Enter => "\n",
            PS2ScanCode::LeftCtrl => "Left Ctrl",

            // Home row
            PS2ScanCode::A => "A",
            PS2ScanCode::S => "S",
            PS2ScanCode::D => "D",
            PS2ScanCode::F => "F",
            PS2ScanCode::G => "G",
            PS2ScanCode::H => "H",
            PS2ScanCode::J => "J",
            PS2ScanCode::K => "K",
            PS2ScanCode::L => "L",
            PS2ScanCode::Semicolon => ";",
            PS2ScanCode::Apostrophe => "'",
            PS2ScanCode::Backtick => "`",

            // Bottom row
            PS2ScanCode::LeftShift => "Left Shift",
            PS2ScanCode::Backslash => "\\",
            PS2ScanCode::Z => "Z",
            PS2ScanCode::X => "X",
            PS2ScanCode::C => "C",
            PS2ScanCode::V => "V",
            PS2ScanCode::B => "B",
            PS2ScanCode::N => "N",
            PS2ScanCode::M => "M",
            PS2ScanCode::Comma => ",",
            PS2ScanCode::Dot => ".",
            PS2ScanCode::Slash => "/",
            PS2ScanCode::RightShift => "Right Shift",
            PS2ScanCode::KeypadStar => "Keypad *",
            PS2ScanCode::LeftAlt => "Left Alt",
            PS2ScanCode::Space => " ",
            PS2ScanCode::CapsLock => "Caps Lock",

            // Function keys
            PS2ScanCode::F1 => "F1",
            PS2ScanCode::F2 => "F2",
            PS2ScanCode::F3 => "F3",
            PS2ScanCode::F4 => "F4",
            PS2ScanCode::F5 => "F5",
            PS2ScanCode::F6 => "F6",
            PS2ScanCode::F7 => "F7",
            PS2ScanCode::F8 => "F8",
            PS2ScanCode::F9 => "F9",
            PS2ScanCode::F10 => "F10",
            PS2ScanCode::NumLock => "Num Lock",
            PS2ScanCode::ScrollLock => "Scroll Lock",

            // Keypad
            PS2ScanCode::Keypad7 => "Keypad 7",
            PS2ScanCode::Keypad8 => "Keypad 8",
            PS2ScanCode::Keypad9 => "Keypad 9",
            PS2ScanCode::KeypadMinus => "Keypad -",
            PS2ScanCode::Keypad4 => "Keypad 4",
            PS2ScanCode::Keypad5 => "Keypad 5",
            PS2ScanCode::Keypad6 => "Keypad 6",
            PS2ScanCode::KeypadPlus => "Keypad +",
            PS2ScanCode::Keypad1 => "Keypad 1",
            PS2ScanCode::Keypad2 => "Keypad 2",
            PS2ScanCode::Keypad3 => "Keypad 3",
            PS2ScanCode::Keypad0 => "Keypad 0",
            PS2ScanCode::KeypadDot => "Keypad .",
            PS2ScanCode::F11 => "F11",
            PS2ScanCode::F12 => "F12",
            PS2ScanCode::KeyReleased => "",
        }
    }
}
impl fmt::Display for PS2ScanCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.to_str())
    }
}
