#[cfg(feature = "first_stage")]
pub const FIRST_STAGE_OFFSET: u16 = 0x7c00;
#[cfg(feature = "first_stage")]
pub const MASTER_BOOT_RECORD_OFFSET: u16 = FIRST_STAGE_OFFSET + 446;
#[cfg(feature = "first_stage")]
pub const SECOND_STAGE_OFFSET: u16 = FIRST_STAGE_OFFSET + 512;
#[cfg(feature = "first_stage")]
pub const DISK_NUMBER_OFFSET: u16 = 0x7BFE;
#[cfg(feature = "kernel")]
pub const VGA_BUFFER_PTR: u32 = 0xb8000;
#[cfg(feature = "first_stage")]
pub const MEMORY_MAP_LENGTH: u16 = 0x9000;
#[cfg(feature = "first_stage")]
pub const MEMORY_MAP_OFFSET: u16 = MEMORY_MAP_LENGTH + size_of::<u32>() as u16;
#[cfg(feature = "kernel")]
pub const PARSED_MEMORY_MAP_LENGTH: u16 = 0x9500;
#[cfg(feature = "kernel")]
pub const PARSED_MEMORY_MAP_OFFSET: u16 = PARSED_MEMORY_MAP_LENGTH + size_of::<u32>() as u16;
#[cfg(feature = "second_stage")]
pub const KERNEL_OFFSET: u64 = 0xa000;
#[cfg(feature = "second_stage")]
pub const IDENTITY_PAGE_TABLE_L4_OFFSET: usize = 0x10000;
#[cfg(feature = "second_stage")]
pub const IDENTITY_PAGE_TABLE_L3_OFFSET: usize = 0x11000;
#[cfg(feature = "second_stage")]
pub const IDENTITY_PAGE_TABLE_L2_OFFSET: usize = 0x12000;
#[cfg(feature = "second_stage")]
pub const TOP_IDENTITY_PAGE_TABLE_L3_OFFSET: usize = 0x13000;
#[cfg(feature = "second_stage")]
pub const TOP_IDENTITY_PAGE_TABLE_L2_OFFSET: usize = 0x14000;
#[cfg(feature = "kernel")]
pub const PAGE_ALLOCATOR_OFFSET: usize = 0x15000;
#[cfg(feature = "kernel")]
#[cfg(target_arch = "x86_64")]
pub const PHYSICAL_MEMORY_OFFSET: usize = 0xffff800000000000;
